# Generated by Django 4.2.1 on 2023-06-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactions',
            name='stock_symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks', to_field='stock_symbol'),
        ),
    ]
